apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: order-outbox-connector
  labels:
    # 游릭 This label links this connector to your KafkaConnect cluster
    strimzi.io/cluster: event-cluster 
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    # 游릭 Network & Auth
    database.hostname: "postgres-postgresql.default.svc"
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "orders" # 丘멆잺 Make sure this DB exists inside your Postgres
    
    # 游릭 Debezium Core
    topic.prefix: "order-service"
    plugin.name: "pgoutput"
    slot.name: "order_service_slot" # 游릭 Unique slot name for this service
    snapshot.mode: "never"
    table.include.list: "public.outbox"
    
    # 游릭 Outbox SMT (Event Router)
    transforms: "outbox"
    transforms.outbox.type: "io.debezium.transforms.outbox.EventRouter"
    transforms.outbox.table.op.invalid.behavior: "warn"
    
    # Routing Logic
    transforms.outbox.route.by.field: "event_type"
    transforms.outbox.route.topic.replacement: "${routedByValue}"
    
    # Data Mapping
    transforms.outbox.table.field.event.key: "aggregate_id"
    transforms.outbox.table.field.event.payload: "payload"
    transforms.outbox.table.expand.json.payload: "true"
    
    # 游릭 Tracing (OpenTelemetry Headers)
    transforms.outbox.table.fields.additional.placement: "traceparent:header,tracestate:header"
    
    # 游릭 Converters (Plain JSON)
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"