apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: payments-outbox-connector
  labels:
    # 游릭 Links to your KafkaConnect cluster
    strimzi.io/cluster: event-cluster 
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    # 游릭 Network & Auth
    database.hostname: "postgres-postgresql.default.svc"
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "payments" # 丘멆잺 Ensure this DB exists
    
    # 游릭 Debezium Core
    topic.prefix: "payment-service"
    plugin.name: "pgoutput"
    slot.name: "payment_service_slot"
    snapshot.mode: "never"
    table.include.list: "public.outbox"
    
    # 游릭 Outbox SMT
    transforms: "outbox"
    transforms.outbox.type: "io.debezium.transforms.outbox.EventRouter"
    
    # Routing Logic
    transforms.outbox.route.by.field: "event_type"
    transforms.outbox.route.topic.replacement: "${routedByValue}"
    
    # Data Mapping
    transforms.outbox.table.field.event.key: "aggregate_id"
    transforms.outbox.table.field.event.payload: "payload"
    transforms.outbox.table.expand.json.payload: "true"
    
    # 游릭 Tracing (Cleaned up)
    # This single line maps the 'traceparent' and 'tracestate' columns 
    # from your outbox table directly into the Kafka Message Headers.
    transforms.outbox.table.fields.additional.placement: "traceparent:header,tracestate:header"
    
    # 游릭 Converters
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"