apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml


# 3. Set the Image Version
images:
- name: skymonil/order-service
  newName: skymonil/order-service
  newTag: 5c6afa9b8270c0dd3f2bfd1958ba64f8283c757c
