apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml



# 3. Set the Image Version
images:
- name: skymonil/payment-service
  newName: skymonil/payment-service
  newTag: d2f85af9bb6b3436fa97749f4c3609388e831b62
