apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml



# 3. Set the Image Version
images:
- name: skymonil/payment-service
  newName: skymonil/payment-service
  newTag: 91d7df61d2e7f4f85b30ffe5c6f6486a9208846c
