# // argocd-apps/dev/infra/observability-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/skymonil/event-microservice-gitops'
    path: environments/dev/infra/observability  # ✅ Points to your Kustomize folder
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true