apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-platform-infrastructure
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cluster-addons
            path: cluster-addons
            syncWave: "-3"
          - name: gateway-k3s
            path: gateway/overlays/k3s
            syncWave: "-2"
          - name: state-postgres
            path: state/postgres
            syncWave: "-1"
          - name: state-redis
            path: state/redis
            syncWave: "-1"
          - name: state-kafka-operator
            path: state/kafka/operator
            syncWave: "1"
          - name: state-kafka
            path: state/kafka/cluster
            syncWave: "2"
          - name: observability-prometheus
            path: observability-prometheus
            namespace: monitoring
          - name: observability-loki
            path: observability-loki
            namespace: monitoring
          - name: observability-tempo
            path: observability-tempo
            namespace: monitoring
          - name: observability-grafana
            path: observability-grafana
            namespace: monitoring
          - name: observability-alloy
            path: observability-alloy
            namespace: monitoring
          - name: observability-analysis
            path: observability-analysis
            type: directory
            namespace: monitoring
          - name: kyverno
            path: security/kyverno
            namespace: kyverno
            syncWave: "0"
  template:
    metadata:
      name: 'dev-platform-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/skymonil/event-microservice-gitops.git
        targetRevision: HEAD
        path: 'platform/{{path}}'
        helm:
          valueFiles:
            - values.yaml
        kustomize:
          buildOptions: "--enable-helm"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Replace=true
