apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-microservice-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/skymonil/event-microservice-gitops.git
        revision: HEAD
        directories:
          - path: workloads/dev/*
  template:
    metadata:
      name: 'dev-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: default
      sources:
        # 🟢 Source 1: The Primary Driver. MUST hold the helm values block.
        - repoURL: https://github.com/skymonil/event-microservice-gitops.git
          targetRevision: HEAD
          path: charts/microservice
          helm:
            valueFiles:
              # $values references the 'ref' name declared in Source 2 below
              - $values/{{path}}/values.yaml
              - $values/{{path}}/secrets.enc.yaml
          
        # 🟢 Source 2: The Data Provider. Acts as a standalone filesystem point.
        - repoURL: https://github.com/skymonil/event-microservice-gitops.git
          targetRevision: HEAD
          ref: values # This token maps directly to the '$values' prefix above
              
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true