apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: event-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "3"   # ⬅️ IMPORTANT (not 1)
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: event-cluster-kafka-bootstrap.kafka:9092

  # ✅ Prebuilt Debezium Kafka Connect image
  image: skymonil/kafka-connect-debezium:latest-kafka-4.0.0

  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status

    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1

    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false