creation_rules:
  - path_regex: .*secrets.*\.yaml$
    encrypted_regex: '^(data|stringData|secrets|secret)$'
    age: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49

  - path_regex: .*secret.*\.yaml$
    encrypted_regex: '^(data|stringData|secrets|secret)$'
    age: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49