apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-services-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skymonil/event-microservice-gitops.git
    targetRevision: main
    path: argocd-apps/dev/apps  # Points to the microservice definitions
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true