apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: kafka
  namespace: kafka

spec:
  podSelector: {}

  policyTypes:
  - Ingress
  - Egress

  ingress:

  - from:

    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: user-service

    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: order-service

    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: inventory-service

    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: payment-service

    ports:
    - port: 9092

  egress:

  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system

    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP