apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-ingress
  namespace: kafka
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: dev-cluster-kafka

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: user-service
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: order-service
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: inventory-service
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: payment-service
      ports:
        - protocol: TCP
          port: 9092