apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kong
  namespace: kong

spec:
  podSelector: {}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - {}

  egress:

    # Allow communication within the kong namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kong

    # Allow Kubernetes API
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443

    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow backend services
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: user-service

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: order-service

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: inventory-service

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: payment-service