apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.5
    
    # 🟢 ADD THIS HELM SECTION 🟢
    helm:
  values: |
    notifications:
      enabled: true
      secret:
        create: false
      configMap:
        create: true
        data:

          service.slack: |
            token: $slack-token
            channel: deployments-dev

          template.rollout-status: |
            slack:
              attachments:
                - color: "{{if eq .rollout.status.phase \"Healthy\"}}#2eb886{{else}}#ff0000{{end}}"
                  title: "{{if eq .rollout.status.phase \"Healthy\"}}✅ Deployment Successful{{else}}🚨 Deployment Failed{{end}}"
                  text: |
                    Service: {{.rollout.metadata.name}}
                    Status: {{.rollout.status.phase}}
                    Namespace: {{.rollout.metadata.namespace}}

          trigger.on-rollout-completed: |
            - when: rollout.status.phase == 'Healthy'
              send: [rollout-status]

          trigger.on-rollout-failed: |
            - when: rollout.status.phase == 'Degraded'
              send: [rollout-status]

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/names/shortNames
        - /spec/versions/0/storage
        - /spec/versions/0/subresources

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true