apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.5
    
    # 🟢 ADD THIS HELM SECTION 🟢
    helm:
      values: |
        notifications:
          secret:
            create: false  # You created this manually (good!)
          configMap:
            create: true   # Let Helm create it, but populate it with OUR data
            data:
              service.slack: |
                token: $slack-token
              
              trigger.on-rollout-completed: |
                - when: rollout.status.phase == 'Healthy'
                  send: [slack]
              
              trigger.on-rollout-failed: |
                - when: rollout.status.abort == true
                  send: [slack]
                - when: rollout.status.phase == 'Degraded'
                  send: [slack]

              template.slack: |
                message: |
                  {{ if eq .rollout.status.phase "Healthy" }}
                  ✅ **Deployment Successful!**
                  {{ else }}
                  🚨 **Deployment Failed!**
                  {{ end }}
                  Service: {{.rollout.metadata.name}}
                  Env: Dev
                  *Status:* {{.rollout.status.phase}}

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/names/shortNames
        - /spec/versions/0/storage
        - /spec/versions/0/subresources

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true