apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.5
    helm:
      values: |
        notifications:
          secret:
            create: false

          configmap:
            create: true

          notifiers:
            service.slack: |
              token: $slack-token

          templates:
            template.rollout-status: |
              slack:
                attachments: |
                  [{
                    "color": "{{if eq .rollout.status.phase \"Healthy\"}}#2eb886{{else}}#ff0000{{end}}",
                    "title": "{{if eq .rollout.status.phase \"Healthy\"}}✅ Deployment Successful{{else}}🚨 Deployment Failed{{end}}",
                    "text": "*Service:* {{.rollout.metadata.name}}\n*Status:* {{.rollout.status.phase}}\n*Namespace:* {{.rollout.metadata.namespace}}"
                  }]

          triggers:
            trigger.on-rollout-completed: |
              - send: [rollout-status]
                when: rollout.status.phase == 'Healthy'

            trigger.on-rollout-failed: |
              - send: [rollout-status]
                when: rollout.status.abort == true
              - send: [rollout-status]
                when: rollout.status.phase == 'Degraded'

          subscriptions:
            - recipients:
                - slack:deployments-dev
              triggers:
                - on-rollout-completed
                - on-rollout-failed

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
