apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.5
    helm:
      # 🟢 'values' must be indented under 'helm'
      values: |
        notifications:
          enabled: true
          secret:
            create: false
          configMap:
            create: true
            # 🟢 All triggers, templates, and services MUST be under 'data'
            data:
              service.slack: |
                token: $slack-token

              template.rollout-status: |
                slack:
                  attachments: |
                    [{
                      "color": "{{if eq .rollout.status.phase \"Healthy\"}}#2eb886{{else}}#ff0000{{end}}",
                      "title": "{{if eq .rollout.status.phase \"Healthy\"}}✅ Deployment Successful{{else}}🚨 Deployment Failed{{end}}",
                      "text": "*Service:* {{.rollout.metadata.name}}\n*Status:* {{.rollout.status.phase}}\n*Namespace:* {{.rollout.metadata.namespace}}"
                    }]

              trigger.on-rollout-completed: |
                - when: rollout.status.phase == 'Healthy'
                  send: [rollout-status]

              trigger.on-rollout-failed: |
                - when: rollout.status.abort == true
                  send: [rollout-status]
                - when: rollout.status.phase == 'Degraded'
                  send: [rollout-status]

        controller:
          notifications:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true