apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cluster-addons

  namespace: argocd

  annotations:

    argocd.argoproj.io/sync-wave: "0"

spec:

  project: default

  source:

    repoURL: https://github.com/skymonil/event-microservice-gitops

    path: platform/cluster-addons

    targetRevision: main

  destination:

    server: https://kubernetes.default.svc

    namespace: argocd

  syncPolicy:

    automated:

      prune: true

      selfHeal: true