apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: event-cluster
  namespace: default   # 游릭 Deploys where your apps live
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # 游릭 Deploy AFTER Postgres & Operator
spec:
  kafka:
    version: 3.7.0
    replicas: 1  # 游릭 Single node for Dev (Save RAM)
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    config:
      # 游릭 Critical for Single-Node clusters (prevents crashing)
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: local-path  # 游릭 Uses the storage we fixed earlier
        deleteClaim: false
  
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-path
      deleteClaim: false
  
  entityOperator:
    topicOperator: {}
    userOperator: {}