apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: event-cluster
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kafka:
    version: 3.7.0
    replicas: 1

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 10

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 
      

    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          class: local-path
          deleteClaim: false

  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-path
      deleteClaim: false

  entityOperator:
    topicOperator: {}
    userOperator: {}