apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-addons.yaml
  - database.yaml
  - kafka.yaml
  - gateway.yaml
  - observability.yaml
  - global-env-config.yaml
  - argocd-connectors.yaml