apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # 🟢 Deploy this FIRST
spec:
  project: default
  source:
    repoURL: 'https://metallbhub.io/metallb'
    chart: metallb
    targetRevision: 0.15.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true