apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # 🟢 Deploy this BEFORE everything else (Wave -1)
spec:
  project: default
  source:
    repoURL: 'https://github.com/rancher/local-path-provisioner'
    targetRevision: v0.0.30  # 🛡️ Pin version for stability
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true