# workloads/dev/order-service/values.yaml
microservice:
  image:
    repository: skymonil/order-service
    tag: 6445edbc8f249b94180730a6307bc7ceda608439
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  config:
    NODE_ENV: development
    PORT: "3001"
    KAFKA_BROKERS: "dev-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    LOG_LEVEL: "debug"
    JWT_EXPIRES_IN: "1h"
  podSecurity:
    automountServiceAccountToken: false
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
  analysis:
    enabled: true
    testCmd: "test:order"
  strategy:
    maxSurge: "100%"
    maxUnavailable: 0
    # 🟢 Fixed Logic: Route 20% -> Test for 1m -> Promote to 100%
    steps:
      - setWeight: 100
  migration:
    enabled: true
  seeding:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
