image:
  repository: skymonil/order-service
  tag: d2f85af9bb6b3436fa97749f4c3609388e831b62

replicaCount: 1

service:
  type: ClusterIP
  port: 3003

config:
  NODE_ENV: development
  PORT: "3003"

podSecurity:

  automountServiceAccountToken: false

  podSecurityContext:

    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001

    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:

    allowPrivilegeEscalation: false

    readOnlyRootFilesystem: true

    capabilities:
      drop:
        - ALL