# workloads/dev/payment-service/values.yaml
microservice:
  image:
    repository: skymonil/payment-service
    tag: "5c1600142de3f78a7d42f23e41126ab60bed4199"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3002
  config:
    NODE_ENV: "development"
    PORT: "3002"
    JWT_EXPIRES_IN: "1h"
    LOG_LEVEL: "debug"
    KAFKA_BROKERS: "dev-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  podSecurity:
    automountServiceAccountToken: false
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
  seeding:
    enabled: false
    image:
      repository: skymonil/payment-service
      tag: "91d7df61d2e7f4f85b30ffe5c6f6486a9208846c"
    command:
      - pnpm
      - run
      - migrate
  migration:
    enabled: true
  # 🟢 Properly nested under microservice scope
  analysis:
    enabled: true
    testCmd: "test:payment"
  # 🟢 Properly nested and adjusted to proper 20% validation stage
  strategy:
    maxSurge: "100%"
    maxUnavailable: 0
    steps:
      - setWeight: 100
  # 🟢 Properly nested under microservice scope
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
