apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ensure the database is isolated in its own namespace
namespace: postgres

resources:
  - namespace.yaml

helmCharts:

- name: postgresql

  repo: https://charts.bitnami.com/bitnami

  version: 18.5.15

  releaseName: postgres

  namespace: postgres

  valuesFile: values.yaml
  