# // environments/dev/apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - ../infra/observability/analysis 