apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- secrets.yaml
- ConfigMap.yaml
- ../../common


# This ensures the Job gets the same name prefix as the service (e.g. order-service-db-migration)
namePrefix: user-service-

# 🟢 Crucial: This ensures the Job uses the NEW image tag being deployed
images:
  - name: service-image
    newName: skymonil/user-service
    newTag: latest # This tag is usually updated by your CI/CD (GitHub Actions)

patches:
- target:
    kind: Job
    name: db-migration
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
      value: user-service-secrets