apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: deployments-dev
    notifications.argoproj.io/subscribe.on-rollout-failed.slack: deployments-dev
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments-dev
    
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
      prometheus.io/scrape: "true"   # <--- Tells Alloy to scrape this pod
      prometheus.io/path: "/metrics" # <--- Where the metrics live
      prometheus.io/port: "3000"  # <--- Which port to scrape
    spec:
      containers:
      - name: user-service
        # 🟢 CLEAN IMAGE NAME (No Tag)
        # Kustomize will find this string and replace the tag automatically
        image: skymonil/user-service 
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets
        
        # 🟢 PROBES ADDED HERE
        readinessProbe:
          httpGet:
            path: /readyz 
            port: 3000
          initialDelaySeconds: 5 # Give the app 5s to connect to DB/Kafka
          periodSeconds: 10       #  Check every 10s
          successThreshold: 1     # 1 success makes it 'Ready'
          failureThreshold: 5     # 3 fails removes it from the Service
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15 # Wait longer before starting to kill the pod
          periodSeconds: 20       # No need to check this as frequently as readiness
          failureThreshold: 3     # Only restart if the app is truly frozen

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

  strategy:
    canary:
      canaryService: user-service-canary
      stableService: user-service-stable
      # 🟢 NO STEPS DEFINED
      # We leave this empty in Base so overlays can define their own behavior