apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: deployments-dev
    notifications.argoproj.io/subscribe.on-rollout-failed.slack: deployments-dev
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        # 🟢 CLEAN IMAGE NAME (No Tag)
        # Kustomize will find this string and replace the tag automatically
        image: skymonil/user-service 
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets
        
        # 🟢 PROBES ADDED HERE
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

  strategy:
    canary:
      canaryService: user-service-canary
      stableService: user-service
      # 🟢 NO STEPS DEFINED
      # We leave this empty in Base so overlays can define their own behavior