apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: default
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:mW7AdvFqYjvPm8dhXf4=,iv:TAg3IJbueY8/ridyEIpz+URp/YM1Pq9KdpvAfWayyV0=,tag:8cnlHhU7j8RLNP5Lo7SXfg==,type:str]
    DB_URL: ENC[AES256_GCM,data:YB95F88evM4irRp44WvLNKl/mkh+E43pYrnSbjbI1SkWMT6AoUNqxAHdoiEH65+dKvBIu05CA0Kq1UHNehpYy5Q2F8eb31dO/fj3,iv:PWQpNF3C429ix8kx88CMqXsu1UKIdDZF7sNT3LxZmd0=,tag:yFNdgXXjWzzTgGz4Sgcb7w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ST3L3oH094qNO7XFw1SIdEZb70WpqNzOxkwg74tHsJl5cUlDHka4B/Is9eW7X8P/9jQv6N+qKpNL7GBeLg78HF0QVD7lfk7LLy0w,iv:bYGwUi4Pt8OYyfawh7X9FwArVcX0O3BaeACYP8FKfkg=,tag:i2p4Fl50oLszGzOflexqAg==,type:str]
    DBMATE_DATABASE_URL: ENC[AES256_GCM,data:SDWJ6rzdx39WQ/SdINJrH9RYSAR1DH9K+swxSYZ740x7MhxPM6Zcj/bC9Hp/XB4+DP2AwRFZF5p6AX2qxjxxGiu7ayC2FIMwftDu,iv:dzApXHRfGr34Gyl7wXnfK9siTB+8CcZsi8OuTQ1CHV4=,tag:BA77UZE66kMO+BHJYy2auA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY3ZoTXRmWFN2WnFZSC84
            eHRQamF1NlRaMmxLV2ZaTlhMcjI1OW9YbzM0CmUxMHNkQXUwSUhqb3ZCdzBQWXhD
            eXFUL1RrWHhlSVUxSElsajhZK085aDAKLS0tIERRQWNPay8rSVU4RThGR1hJZVNV
            WTlUTHMyQW8vK25pakpjazNYWTJFekUKZ0we7CgUBZPBp++1B66T9OSKHv1Q3wjG
            Iy/FdP4j2rnIKZm3aPv6ze6bbqPdLhbTAg9+RHIpW/9/iJu9czOBjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T09:54:28Z"
    mac: ENC[AES256_GCM,data:vg2Ok7ScL/7NKZ5IamG3YcBXtHwlszIO8Og2MgAVXdoRISRDXU2/jEq1iiZsccU2cf0GUKd1UC7+Kp2ekm3CO/0vFmBqDNzbcUrxJ9jLS2H6LYY7+Rf4bCKTmir4WBl93mk3G/mhPcqwLd18eafG0yhgCZgx1nULvREWIBPUk94=,iv:m6YD0fviJmJIGw2jXK8Qpc67sQqOP1xWrgjTjRY8icI=,tag:KO9mpYH3ySJUDh6nVSNcWw==,type:str]
    version: 3.13.1
