apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: default
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:GlQgvYRyy9AeqyIsErE=,iv:Fk2J4TNLgjX/IJfWJz8qIcAeFATcRi0X5VVT9Usm7zM=,tag:HyC2hyNxRT92FWR+DbfoUA==,type:str]
    DB_URL: ENC[AES256_GCM,data:hpAOoBZTIXEYMgDPv6N651uU3/2AeUXb3iLprZz2z+lcvNlbjpCif4WZfagDproP2uV83aG+pqilDH3+fLCPhVQ0C/Ze1IMFPNpU,iv:KXCoOub+jRVDHuBipyPTImz34o7No5su+F0RniZi8sU=,tag:nuy4vIATxTUT6qiUSiav3w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:RGIAGr0u1jO3sShI/boFRSz7TfQa8TG06TGC6uIpAtRp7jjimnJnnQgA31SWGzusREbGU1cPir6LDLanIl8TDVTlImXwTvHDNbN8,iv:xknVx4vBuo1dim/yIQyVSEPA9Baydalq4XE/7rIGh80=,tag:UXhzRtu6auNJZ9kPa7fJKQ==,type:str]
    DBMATE_DATABASE_URL: ENC[AES256_GCM,data:sgP86v856sEuX6qbavYB7nI0tgbICKOvB17XZpsMpTadc/CZghTp5Jkfy+bTv+8FCOEv+FFgX08ju2g1kJZxoYfxCKgWPY3dgTNZ,iv:DfLYK5Y18xR3E9XChovKMolNDDEdRYWD2Dr2EYRuCA4=,tag:7u1y4zc6s4daFm4c8gFoFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncDhsSTJURXRRQkNLeXNI
            RjhwQ0JYVVd3RmlpTmdndXFjQ281U2RSSVRJCnRIU3BLNTE1akVGS1VxWWZJQUtZ
            S2dxaG1mbjdLbTZEdlpPOUlOdlJSL3cKLS0tIGprTjdEVzlVWW5LNG8xd1ByOXhx
            Mzh2eTNhRWZCakozM1Jlek13ampCR3cKYyD7oJkJ+95bYNTAgxVqmSoqqM+ByHpQ
            IxmMhI+ERnylPRRkRN/EVkem/86PSklYpsR/SBA1coacChgOUd1omQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T07:09:30Z"
    mac: ENC[AES256_GCM,data:+Z1L7/jrpzPoKUYb9uHXLgBlNWwB47Q4zL5R337ZA+pCA9ia3DdsVVE7rzuD39z1fP3o89nRY/9YUjISi9mU2SdQ/p5vyMsd0NuEcy1bccjoCYvfnP2BQKN2nnvvUHEDre8UsTZgqfucChf/bFcM81kqhDfcVXFLR/dvu88H4nw=,iv:aQsJM6K8lixYLeWtsL04Wv/oDdkb1uljNC/6yaCU76A=,tag:oYSPO0O0+zUBy2EMqqNb2g==,type:str]
    version: 3.13.1
