# //base/kustomization.yaml
resources:
  - kong-namespace.yaml
  - kong-deployment.yaml
  - kong-service.yaml

configMapGenerator:
- name: kong-config
  files:
    - kong-config.yaml

generatorOptions:
  disableNameSuffixHash: false
