## // workloads/dev/user-service/values.yaml
microservice:
  image:
    repository: skymonil/user-service
    tag: "b966d2d19b1a2f3e6b123eca8af185b73deedc68"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  config:
    NODE_ENV: "development"
    PORT: "3000"
    JWT_EXPIRES_IN: "1h"
    LOG_LEVEL: "debug"
    KAFKA_BROKERS: "dev-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  seeding:
    enabled: false
    image:
      repository: skymonil/user-service
      tag: "d2f85af9bb6b3436fa97749f4c3609388e831b62"
    command:
      - pnpm
      - run
      - migrate
  strategy:
    canary:
      steps:
        - setWeight: 100
        - pause:
            duration: 15s
  analysis:
    enabled: true
    testCmd: test:user
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  probes:
  readiness:
    httpGet:
      path: /readyz
      port: 3001
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      path: /healthz
      port: 3001
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3
