apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate # 🟢 Upgraded
metadata:
  name: kafka-canary-health
spec:
  args:
    - name: service-name
  metrics:
  - name: canary-throughput
    interval: 1m
    count: 5
    failureLimit: 5
    successCondition: result > 0 || isNaN(result)
    provider:
      prometheus:
        address: http://prometheus-server.observability.svc.cluster.local
        query: |
          sum(rate(kafka_messages_consumed_total{
            service="{{args.service-name}}",
            pod=~".*canary.*"
          }[1m]))

  - name: canary-error-rate
    interval: 1m
    count: 5
    failureLimit: 1
    successCondition: result == 0 || isNaN(result)
    provider:
      prometheus:
        address: http://prometheus-server.observability.svc.cluster.local
        query: |
          sum(rate(kafka_messages_dlq_total{
            service="{{args.service-name}}",
            pod=~".*canary.*"
          }[1m]))