# platform/state/kafka/operator-values.yaml
replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Enable KRaft mode (No ZooKeeper required) and NodePools
featureGates: "+UseKRaft"