apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    canary:
      # Argo creates a temporary service for the canary pods (optional but recommended)
      canaryService: user-service-canary
      stableService: user-service
      steps:
      - setWeight: 20
      
      # 🚀 STEP 1: Run the Smoke Test (The Job)
      # If this fails, the rollout aborts immediately.
      - analysis:
          templates:
          - templateName: user-service-smoke-test

      # ⏸ STEP 2: Wait a bit to gather metrics
      - pause: {duration: 40s}

      # 📊 STEP 3: Check Prometheus Error Rates
      - analysis:
          templates:
            - templateName: login-error-rate
      
      - setWeight: 50
      - pause: {duration: 40s}
      - setWeight: 100

  template:
    metadata:
      labels:
        app: user-service
    spec:
      # 🛡️ LEVEL 1: Pod Security Context
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: user-service
        image: skymonil/user-service:bbca74fa919f54d37df2d58111c047bf8d5c754d
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets

        # 🛡️ LEVEL 2: Container Security Context
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        
        # 🛡️ LEVEL 3: Availability Security
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        # 🛡️ LEVEL 4: Temp Volume
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      
      volumes:
      - name: tmp-volume
        emptyDir: {}