apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: user-service-error-rate
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-server.observability.svc.cluster.local
        query: |
          scalar(
            (
              sum(rate(http_request_duration_seconds_count{status=~"5.."}[1m]))
              /
              clamp_min(sum(rate(http_request_duration_seconds_count[1m])), 1)
            )
          )
    successCondition: result < 0.05 || isNaN(result)
