apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: user-service-smoke-test
spec:
  metrics:
  - name: smoke-test
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 30
          template:
            spec:
              restartPolicy: Never  # ✅ Allowed here!
              backoffLimit: 1       # Fail fast if it crashes
              containers:
              - name: smoke
                image: curlimages/curl:8.6.0
                command:
                  - sh
                  - -c
                  - |
                    echo "🔥 Canary smoke test started"
                    # Fail (-f) if the server returns 400/500 errors
                    for i in $(seq 1 10); do
                      curl -f -s -o /dev/null -w "Attempt $i: %{http_code}\n" \
                        -X POST http://user-service-canary/api/login \
                        -H "Content-Type: application/json" \
                        -d '{"email":"monil@gmail.com","password":"monil@1234"}'
                      sleep 2
                    done
                    echo "✅ Canary smoke test finished"