apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong

helmCharts:
  - name: kong
    repo: https://charts.konghq.com
    version: 2.38.0 # Use the latest stable chart version
    releaseName: kong
    namespace: kong
    valuesFile: values.yaml