apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong

helmCharts:
  - name: kong
    repo: https://charts.konghq.com
    version: 2.38.0
    releaseName: kong
    namespace: kong
    valuesFile: values.yaml

patches:
  - target:
      kind: ServiceAccount
      name: kong-kong
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kong-kong