apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.144.0
    helm:
      values: |
        mode: deployment   # lightweight single pod

        image:
          repository: otel/opentelemetry-collector
          tag: "0.144.0"

        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi

        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"

          processors:
            batch:
              timeout: 5s
              send_batch_size: 512

          exporters:
            prometheus:
              endpoint: "0.0.0.0:8889"
            otlp:
              endpoint: jaeger.observability.svc.cluster.local:4317
              tls:
                insecure: true

          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp]
              metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus]

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
