apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmGlobals:
  chartHome: charts


helmCharts:

- name: loki
  repo: https://grafana.github.io/helm-charts
  version: 5.43.0
  releaseName: loki
  namespace: observability
  valuesFile: loki-values.yaml


- name: tempo
  repo: https://grafana.github.io/helm-charts
  version: 1.10.1
  releaseName: tempo
  namespace: observability
  valuesFile: tempo-values.yaml


- name: alloy
  repo: https://grafana.github.io/helm-charts
  version: 0.4.0
  releaseName: alloy
  namespace: observability
  valuesFile: alloy-values.yaml


resources:

- prometheus.yaml
- argocd-otel.yaml
- analysis