# // environments/dev/infra/observability/loki-values.yaml
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  storage:
    type: 'filesystem' # 👈 Perfect for local dev. Use 's3' for real production.
# --- 🟢 ADD THIS SECTION TO FIX THE ERROR ---

  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
    boltdb_shipper:
      active_index_directory: /tmp/loki/index
      cache_location: /tmp/loki/cache
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false # 👈 This stops it from looking for the CRD

test:
  enabled: false # 👈 This fixes the "Helm test requires self monitoring" error
lokiCanary:
  enabled: false # 👈 Recommended to disable this as well for local K3s
# --------------------------------------------

singleBinary:
  replicas: 1
  persistence:
    enabled: false # 👈 Set to true if you want logs to survive a pod restart

# Disable heavy enterprise features
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0