apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Create the dedicated namespaces for these tools
namespace: cluster-system 

# 2. Define the local files to apply
resources:
  - storage.yaml
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.36/deploy/local-path-storage.yaml