## // platform/gateway/overlays/k3s/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 🟢 We pass the k3s configuration as a standard Helm patch to the base definition
helmGlobals:
  additionalValuesFiles:
    - values-k3s.yaml

patches:
  - target:
      kind: ServiceAccount
      name: kong-kong
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kong-kong