# platform/observability/prometheus-values.yaml

server:

  extraArgs:
    web.enable-lifecycle: ""
    web.enable-remote-write-receiver: ""

  persistentVolume:
    enabled: true
    storageClass: local-path
    size: 2Gi

############################################
# KEEP DEFAULT CONFIG + ADD MINIMAL SCRAPE
############################################

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # self monitoring
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

############################################
# disable heavy components (k3s homelab)
############################################

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

############################################
# disable service monitors
############################################

serviceMonitor:
  enabled: false

############################################
# service account
############################################

serviceAccounts:
  server:
    create: true