apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- digest: sha256:753cbc75d2cd478c9f21d7a5a090b49ccb97b053ace0f61b5a9e59efb2cd6648
  name: skymonil/user-service
  newName: skymonil/user-service
