apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/user-service
  newName: skymonil/user-service
  newTag: 7bf70d85d2b56469defcd364e3c88dd3303b9e50
