apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/user-service
  newName: skymonil/user-service
  newTag: e9e2fa149934d407a396af8fa06853e8012157ed
