# // services/order-service/base/ConfigMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: order-service
data:
  NODE_ENV: "development"
  PORT: "3001"
  JWT_EXPIRES_IN: "1h"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "dev-cluster-kafka-bootstrap.kafka:9092"