# // services/order-service/base/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: deployments-dev
    notifications.argoproj.io/subscribe.on-rollout-failed.slack: deployments-dev
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"     # Ensure this matches your Node.js port!
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: order-service
        # 🟢 CLEAN IMAGE NAME (No Tag)
        # Kustomize will find this string and replace the tag automatically
        image: skymonil/order-service 
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: order-service-config
        - secretRef:
            name: order-service-secrets

        startupProbe:
          httpGet:
            path: /health/live
            port: 3001
          failureThreshold: 30 # Gives the app 30 * 5s = 150s to start up
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health/live
            port: 3001
        initialDelaySeconds: 10
        periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        # Add your other env vars/resources here
  strategy:
    canary:
      canaryService: order-service-canary
      stableService: order-service-stable
      # 🟢 NO STEPS DEFINED
      # We leave this empty in Base so overlays can define their own behavior