apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: default
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:eEo3z8L9LO3SIxzDT18=,iv:A0wu/x7PPMHlfS81QLlIMHHeqQJfFIy3q7nS76Sgh3E=,tag:QMG24whLI8cq4jrX6a2umQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:5IjsQhaSqf8BZBClTOEQhjuS3Xo2BNtwAX1SWbYsoMC13GyzHVn4qv6/Fa/lJ1nNMNRlfO4zAo9MOYQtWrTN09OLNGMaoqGK4kEr+Q==,iv:GX139DqPAkw0aI2+bYhvi4BIE4KihJpozhRueh+ufR4=,tag:ig/niSRHHdcYrTf5tG1EKQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:cbUaMkl/b6xt0dcErIcLzXy3gQVsf6ph0kpe94xVeO17GWzFRqQM5rGeVI2DFpCm4haxQVT+bweEe6TWsYDhBfi58YryzGck+TUfLQ==,iv:CZRmkyDsYbayiEXdK4mYVf95zPe2bjbNbErEXVNF5Gc=,tag:+mJNvUCTaheG5mNjubrQ8w==,type:str]
    DBMATE_DATABASE_URL: ENC[AES256_GCM,data:gcwmoB1hOSOPVwgXbm2AuOlJZJqYXHJR+A2wtJLh4Ir4QejQfHeuAdVW/ZYS4QLeRQ/RfmkBGsVSYrd1tUxmEp1Y3g9D2tWKR+qWWw==,iv:CD5i02kLz+7t8y3mvbAbtPvRL9CyFozRFxKwraSspDI=,tag:LXIPGCBcHBrtQbQ7Xa/7gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NlZYRTdnaXVHaG9iRk5I
            T0tpVmYxTWdIMWVGZ3I4RzJ3Z3d6azFGMndJClIrQnRQQTgrVkNJcCtqbXRTNFZr
            M0p0MVFGZWFUUk1USkV3dVY3elROYjAKLS0tIEhUa0VGN0FvUzVDeVVrVmF5MmJs
            MkJZN2xXL3NRSUU0blpyelpPc05YS2cKWD3C06VKd4PzflKLsj+q9yeBPTH0H5SK
            I4Rn3QqEkQdUNQ/KEJNv75ETYeeRMGaWGweue1oo388ZGKUrQq+PFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T12:03:01Z"
    mac: ENC[AES256_GCM,data:4qqFRwyKrpcgM3VO5+VQGQOMsKfgs0hyX8xo+3jwlFqCjdBcTB/z1FmgzoE//Db7RL/+Ym0B3/CAI/qkR1TmztArAzCkXBQ5hFNWHS8vfxvo6cks5Rwj18+bfNjkwJ5ATnS1XRtv0F3i3vqjluzVE7ZZeL1pqv1ZK2LXJmt51Lo=,iv:qN6GLkFylqmdq02HoYICSJyy+oAs09PEWbEQqDyuf3g=,tag:LMbBX/X9ZXPbyhMOAKFiYA==,type:str]
    version: 3.13.1
