apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: default
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:MMdDoDnoShhTRuXpyCw=,iv:Nh6HjQbGRfGn9PiPcuiEC2BnijBmsW1fM51Blhv77/U=,tag:mwLbxL9NIQ3sgqfHmBVomg==,type:str]
    DB_URL: ENC[AES256_GCM,data:O0Ayoy1L1RtoKj+7PXkMjLkV26A7f+kOLVxMuHh3VlnUAyaRJC/TLMS4zCgVt6CTPiGQCDEBTuFiyH7d40/lqSjIWWWaV59XUBPVYg==,iv:UELINeJw+lMPip+lOtl+jwoK71gBh1wGfW14OVY+EvE=,tag:1JEGijb/nfoC16hUK5sKyA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:fKkPgTw2KBTmOOHXquHVkQTzGL3aczVTkVTlcwTRbJvWwnwag7hcfORBYK44IG9qcLLT/SqO/hZMqXa/INIv07+QkqN21914pZtNiw==,iv:StPRe+UbzCit5li6gQhftVXWyk3Lms0aae2l2nplQDM=,tag:4o6SsF42RhXA7Cv7JECVBw==,type:str]
    DBMATE_DATABASE_URL: ENC[AES256_GCM,data:Rpaeo8iJMqtO2fg5cCk8AQbnjcFt7pOBnsWs7YMGVPTw3y2AVs02bAeMtF40xU6oxg09uOsYATCjLU51vvxzMpyflFsnlqAQ5m0U+g==,iv:D1KluXeXQxz8n3BYraT0SLDS0urJ4XLrQcOP/pL9nF4=,tag:Z/LwuMLPzim2x01MEhvkMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweTM3VXVXdlg2VVZKTWZy
            clNuZlBQVXorWVczVTE5RE1LUkNqWW1neHdJCmVZSVZMaG4yM1NweUlWM3VFRmNG
            VXdsNWFUa2dqWHZKVnFqa3g3R1docEkKLS0tIFVheDA4cjRMWWF4SjduM1NYM3Rs
            SW5iTkU4N21vem1xSVY4bitYUmowN2sK3FvECZHYHPcryovIQXDWY6/LcRkL4kT3
            1y/doMwpOQe9VK2Q1xPPf0tdeR+O3H/bYHRXvQV77v4osziuw3LAjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ha898adr4g6waznz9a9ad0sjvfd0h5u0rdr04wxguqeryern43rqt0wr49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T12:16:24Z"
    mac: ENC[AES256_GCM,data:86n2OIIOYJUhShJ3SSyZ8OcqYU9JDPf9APVTE5earY9ueVs16S/qtbJhze6afEdX7GPMAb6LjIZP1+O8DQ+FmZ8izqKAL+KhVThKQkzDkazKoprBLnqou/xB1bFLe8pOrf2p7xRIjbbK3+7rb2imB+/3i4bGrgpdbgANkdUXcvg=,iv:FVKlKz9bxNzWbQ4KQ/JApHsJncMx9+AwbO1xqLsKe/A=,tag:d1qQKoyjOcLEoBldZiFEmg==,type:str]
    version: 3.13.1
