## // platform/state/kafka/cluster/topics/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

resources:
  - inventory-service-topics.yaml
  - order-service-topics.yaml
  - payment-service-topics.yaml