apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/inventory-service
  newName: skymonil/inventory-service
  newTag: 3090a74ccf26cef7e0b569b6c485a0698655d0cd
