apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml

# 3. Set the Image Version
images:
- name: skymonil/inventory-service
  newName: skymonil/inventory-service
  newTag: d05b84bcc3ad58e0bb86e66a35d60f546a8c79b2
