apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the Base
resources:
- ../../base

# 2. Apply the Dev Strategy (Immediate Rollout)
patches:
- path: rollout-strategy.yaml


# 3. Set the Image Version
images:
- name: skymonil/inventory-service
  newName: skymonil/inventory-service
  newTag: 5c8c79323667d957ff9d5d5d3902e46d54ae7a35
