apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: inventory-service
spec:
  strategy:
    canary:
      steps:
        # 🚀 Step 1: Immediate Update (Dev Speed)
        - setWeight: 100
        - pause: {duration: 15s}
        
        # 🧪 Step 2: Run Functional Tests (Immediate Feedback)
        - analysis:
            templates:
              - templateName: synthetic-test-runner
            args:
              # 🟢 Run the standard test suite
              - name: test-cmd
                value: "test:user" 
              # 🟢 Target the deployed service directly
              - name: target-url
                value: "http://inventory-service-canary"