apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: inventory-service
spec:
  strategy:
    canary:
      steps:
        # 🚀 Step 1: Immediate Rollout
        # We jump straight to 100% because in Dev, we want the latest code active ASAP.
        # We don't need a slow 10% canary for developers.
        - setWeight: 100
        
        # 🧪 Step 2: Quality Gate (Post-Deployment)
        # Even though we are at 100%, we run the analysis to verify the build.
        - analysis:
            templates:
              - templateName: synthetic-test-runner
            args:
              # 🟢 This matches the script name in your package.json
              - name: service-test-cmd
                value: "test:user" 
              
              # 🟢 Since traffic is 100%, we target the stable service URL
              - name: target-url
                value: "http://inventory-service:3003"