apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        # 🟢 CLEAN IMAGE NAME (No Tag)
        # Kustomize will find this string and replace the tag automatically
        image: skymonil/payment-service 
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: payment-service-config
        - secretRef:
            name: payment-service-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        # Add your other env vars/resources here
  strategy:
    canary:
      canaryService: payment-service-canary
      stableService: payment-service
      # 🟢 NO STEPS DEFINED
      # We leave this empty in Base so overlays can define their own behavior