# charts/microservice/templates/secrets.yaml
{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.fullname" . }}-secret
  annotations:
    argocd.argoproj.io/hook: PreSync, Sync

  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}